#ifndef default_button_spritesheet_H_INCLUDED
#define default_button_spritesheet_H_INCLUDED
#include "default_button_spritesheet.cpp"
extern size_t __default_button_spritesheet_size;
extern unsigned char __default_button_spritesheet_data[998];
#endif
