#ifndef default_button_d_spritesheet_H_INCLUDED
#define default_button_d_spritesheet_H_INCLUDED
extern size_t __default_button_d_spritesheet_size;
extern unsigned char __default_button_d_spritesheet_data[1004];
#endif
